apiVersion: v1
entries:
  rabbitmq-producer-randomizer:
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2023-11-16T00:18:51.048570818+01:00"
    description: random messages producer for rabbitmq
    digest: c3d66f3e905ecb33ed96fce0868ee9543de2d675a8bbe373bfc8f416eab74fbc
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2023-11-16T00:18:51.048303875+01:00"
    description: random messages producer for rabbitmq
    digest: de667648999b43c589e03d20dd0ac368e664a05e6991269ddbc2727cd70eb262
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v2
    appVersion: 0.0.6
    created: "2023-11-16T00:18:51.048076069+01:00"
    description: random messages producer for rabbitmq
    digest: afe02a6af0a19f8200cd49cde9ade5d75b03b83a4b664b0853e351c0f51f2c40
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v2
    appVersion: 0.0.5
    created: "2023-11-16T00:18:51.047853887+01:00"
    description: random messages producer for rabbitmq
    digest: b968cb564037e57559f73947fdecd539063a4badaa2b8b85b9e4c67e401bd06f
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v2
    appVersion: 0.0.4
    created: "2023-11-16T00:18:51.047636664+01:00"
    description: random messages producer for rabbitmq
    digest: 9f304502cceabf942a9c5f6b49d0d04b4897cc69f1791bf9b8ffd0a16ccf54c3
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2023-11-16T00:18:51.047426666+01:00"
    description: random messages producer for rabbitmq
    digest: 762e9c8f24e3fade2426404203d57dc7db43622cd44fc90e8269931673fff738
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.2
    created: "2023-11-16T00:18:51.047200319+01:00"
    description: random messages producer for rabbitmq
    digest: c43b2e6c75b79a03c390628e52e3141a388dbe8b8c7a5b000362ceb4631e541a
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-11-16T00:18:51.046949752+01:00"
    description: random messages producer for rabbitmq
    digest: e79e3842266fdd200d4edd64d821df03321e3a0c559ca8a01bb4cf1dab23423e
    name: rabbitmq-producer-randomizer
    type: application
    urls:
    - rabbitmq-producer-randomizer-0.0.1.tgz
    version: 0.0.1
generated: "2023-11-16T00:18:51.046427053+01:00"
