apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
type: Opaque
data:
  RABBITMQ_USER: {{ .Values.secret.rabbitmq_user }}
  RABBITMQ_PASSWORD: {{ .Values.secret.rabbitmq_password }}
